BrokerUI/urls.py
from django.conf.urls import url
from BrokerUI import views
from django.urls import path
from rest_framework import routers

urlpatterns = [
    path('estate/',views.EstateListView.as_view(),name='estates'),
    path('new/profile/',views.ProfileCreateView.as_view(),name='new_profile'), # new profile viz broker, user, seller
    path('new/user/',views.CreateUserView.as_view(),name='new_user'), # new user
    path('new/estate/',views.CreateEstateForm.as_view(),name='new_estate'), # new estate
    path('estate/<int:pk>',views.EstateDetailView.as_view(),name='estate_detail'),
    path('estate/<int:pk>/update',views.EstateUpdateView.as_view(),name='estate_update'),
    path('profile/<int:pk>/',views.BrokerDetailView.as_view(),name='broker_detail'),
    path('broker/update/<int:pk>',views.BrokerUpdateView.as_view(),name='broker_update'),
    path('estate/<int:pk>/remove',views.EstateDeleteView.as_view(),name='estate_delete'),
    path('form/estate', views.EstatePricePrediction, name='predform'),
    path('search/',views.query,name='query'),
]

OLXclone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views
import OLXclone.settings as settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SellerUI.urls')),
    path('', include('BrokerUI.urls')),
    path('', include('UserUI.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('accounts/logout/', views.LogoutView.as_view(), name = 'logout', kwargs = {'next_page':'home'}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserUI/urls.py
from django.urls import path
from UserUI.views import *
from django.conf.urls import include

urlpatterns = [
    path('user/vehicles', VehiclesBoughtView.as_view(), name = 'vehicles'), #Home Page
]

BrokerUI/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Profile(models.Model):

    user_types = (
        ('S', 'Seller'),
        ('C', 'Customer'),
        ('B', 'Broker'))
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    phone_number = models.CharField(max_length=10)
    type = models.CharField(max_length = 1, choices = user_types)
    profile_image = models.ImageField(upload_to = 'profile_pics', null = True)


    def __str__(self):
        return self.user.first_name

    def get_absolute_url(self):
        return reverse('broker_detail', kwargs={'pk':self.pk})

class Estate(models.Model):
    choices_furnished = [('yes','yes'),('no','no'),('semi','semi')]
    choices_construction = [('under_construction','under_construction'),('launched','launched'),('ready_to_move','ready to move')]
    type_choices=[('apartments','apartments'),('sale-floors','sale-floors'),('houses','houses')]
    broker = models.ForeignKey(Profile,on_delete=models.CASCADE)
    lat = models.FloatField()
    lon = models.FloatField()
    price = models.FloatField()
    bedroom = models.PositiveIntegerField()
    bathroom = models.PositiveIntegerField()
    carpetarea = models.IntegerField()
    builtuparea = models.IntegerField()
    project = models.CharField(max_length=400,default='can\'t say')
    furnished= models.CharField(max_length=10,choices=choices_furnished,default='can\'t say')
    construction_status = models.CharField(max_length=50,choices=choices_construction,default='can\'t say')
    sublocality = models.CharField(max_length=100,default='can\'t say')
    type=models.CharField(max_length=100,default='can\'t say', choices = type_choices)

    def __str__(self):
        return self.broker.user.first_name

    def get_absolute_url(self):
        return reverse('estate_detail',kwargs={'pk':self.pk})


class Prediction(models.Model):
    spell_choices = [('DISCERN_LOCATION','DISCERN_LOCATION'),('GEAS','GEAS')]
    sublocality_choices= [
        ('Gotri','Gotri'),
        ('Vasna','Vasna'),
        ('Atladara','Atladara'),
        ('Manjalpur','Manjalpur'),('Akota','Akota'),
        ('Karelibaugh','Karelibaugh'),
        ('Danteshwar','Danteshwar'),
        ('Sun Pharma Padra Road','Sun Pharma Padra Road'),
        ('Dabhoi Road','Dabhoi Road'),('Samta','Samta'),
        ('Wadi','Wadi'),('Bhayli','Bhayli'),
        ('Kalali','Kalali'),
        ('Vadsar','Vadsar'),
        ('akshar chowk','akshar chowk')
    ]
    type_choices = [
        ('apartments','apartments'),
        ('sale-floors','sale-floors'),
        ('houses','houses')
    ]
    rooms_choices = [
         (1,1),
         (2,2),
         (3,3)
     ]
    bathrooms_choies = [
        (1,1),
        (2,2),
        (3,3)
    ]
    furnished_choices = [
        ('no','no'),
        ('yes','yes'),
        ('semi','semi')
     ]
    constructionstatus_choices=[
        ('under_construction','under_construction'),
        ('launched','launched'),
        ('ready_to_move','ready_to_move')
    ]
    project_choices=[
        ('Pavilion Heights: PR/GJ/VADODARA/VADODARA/Others/RAA05921/210819','Pavilion Heights'),
        ('Devesh Imperia','Devesh Imperia'),
        ('White lotus','White lotus'),
        ('PRAKRUTI','PRAKRUTI'),
        ('STATUS','STATUS'),
        ('Ananta swagatam','Ananta swagatam'),
        ('Saakar belleza','Saakar belleza'),
        ('SAMRUDDHI','SAMRUDDHI'),
        ('VIHAV SKYONE: PR/GJ/VADODARA/VADODARA/Others/MAA03997/061118','VIHAV SKYONE'),
        ('Gotbull','Gotbull'),
        ('PARAM BLISS','PARAM BLISS'),
        ('Anant park society','Anant park society'),
        ('NAMAN HEIGHTS','NAMAN HEIGHTS'),
        ('PARAM CREST','PARAM CREST'),
        ('Dwarkesh Avenue','Dwarkesh Avenue'),
        ('Girikunj Apartment','Girikunj Apartment'),
        ('GOLDEN VALLEY','GOLDEN VALLEY'),
        ('GUNATIT RESIDENCY','GUNATIT RESIDENCY'),
        ('SHYAMAL COUNTY- TYPE-B','SHYAMAL COUNTY'),
        ('PARAM CREST-PR/GJ/VADODARA/VADODARA/Others/MAA05269/120419','PARAM CREST')
    ]

    spell = models.CharField(max_length = 30, choices = spell_choices)
    sublocality_level = models.CharField(max_length = 100, choices = sublocality_choices)
    lat = models.FloatField()
    long = models.FloatField()
    type = models.CharField(max_length = 15, choices = type_choices)
    rooms = models.IntegerField(choices = rooms_choices)
    bathrooms = models.IntegerField(choices = bathrooms_choies)
    furnished = models.CharField(max_length = 5, choices = furnished_choices)
    constructionstatus = models.CharField(max_length = 50, choices = constructionstatus_choices)
    ft = models.FloatField()
    carpetarea = models.FloatField()
    project = models.CharField(max_length = 150, choices = project_choices)

    def __str__(self):
        return f'{self.project} {self.rooms}'

BrokerUI/forms.py
from django import forms
from BrokerUI.models import Profile,Estate,Prediction
from django.contrib.auth.models import User

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['type','phone_number', 'profile_image']

class UserForm(forms.ModelForm):

    password  = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password' )

class EstateForm(forms.ModelForm):

    class Meta:
        model = Estate
        fields = ['lat','lon','bedroom','bathroom','carpetarea','builtuparea','price', 'project', 'furnished', 'construction_status', 'sublocality', 'type']

class PredictionForm(forms.ModelForm):
    class Meta:
        model=Prediction
        fields='__all__'

class QueryForm(forms.Form):
    broker_name = forms.CharField(label="Broker's name",max_length=100,required=False)
    min_cost = forms.FloatField(label="Min cost",required=False)
    max_cost = forms.FloatField(label="Max cost",required=False)

BrokerUI/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from BrokerUI.forms import ProfileForm,UserForm,EstateForm,PredictionForm
from BrokerUI.models import Profile,Estate,Prediction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponse,JsonResponse
from django.contrib.auth import authenticate,login
from BrokerUI.serializers import PredictionSerializers
import joblib
import pandas as pd
import numpy as np
from django.contrib import messages


class ProfileListView(ListView):
    model = Profile

class ProfileCreateView(LoginRequiredMixin,CreateView):
    form_class=ProfileForm
    login_url = '/login/'
    redirect_field_name = 'BrokerUI/profile_form.html'

    model = Profile
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        # t=form.save(commit=False)
        # print(t)
        print(self.request.user.username)
        print(form.instance.type)
        form.instance.user = User.objects.filter(username=self.request.user.username)[0]
        username = self.request.user.username
        password = self.request.user.password
        print(username,password)
        form.instance.save()
        # t=form.save()
        try:
            return super().form_valid(form)
        except IntegrityError as e:
            messages.error(self.request,message='Profile already created')
            return super().form_invalid(form)

class CreateUserView(CreateView):

    template_name = 'BrokerUI/user_form.html'
    success_url = reverse_lazy('new_profile')
    form_class = UserForm
    model = User
    def form_valid(self, form):

        form.instance.set_password(form.instance.password)
        valid = super(CreateUserView,self).form_valid(form)
        username,password = form.cleaned_data.get('username'),form.cleaned_data.get('password')
        new_user = authenticate(username=username,password=password)
        login(self.request,new_user)
        return valid

class CreateEstateForm(CreateView):
    template_name = 'BrokerUI/estate_form.html'
    success_url = reverse_lazy('home')
    form_class = EstateForm
    model = Estate

    def form_valid(self,form):
        p=Profile.objects.filter(user = self.request.user)[0]
        print(p.user.first_name)
        print(form.instance.price)
        form.instance.broker = p
        print(form.instance.broker.user.username)
        if(form.instance.broker.type != 'B'):
            messages.error(self.request,message='Only brokers can register')
            return super().form_invalid(form)
        try:
            return super().form_valid(form)
        except IntegrityError as e:
            return HttpResponse(e.__cause__)

class EstateListView(ListView):
    model = Estate
    paginate_by=5

class EstateDetailView(LoginRequiredMixin,DetailView):
    login_url = '/login/'
    redirect_field_name = 'BrokerUI/estate_detail.html'
    model = Estate


class EstateUpdateView(UpdateView):
    model = Estate
    template_name = 'BrokerUI/estate_update_form.html'
    form_class = EstateForm


class BrokerDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    # print(Test.pk)
    template_name= 'BrokerUI/broker_detail.html'

class BrokerUpdateView(UpdateView):
    model = Profile
    fields=['phone_number']
    template_name = 'BrokerUI/broker_update.html'

class EstateDeleteView(DeleteView):
    model = Estate
    template_name = 'BrokerUI/estate_delete.html'
    success_url = reverse_lazy('home')


def processing(df):
    regressor = joblib.load('BrokerUI/regressor_model.pkl')
    scalar_for_params=joblib.load('BrokerUI/scalar_for_params.pkl')
    scalar_for_price=joblib.load('BrokerUI/scalar_for_price.pkl')
    one_hot_encoder=joblib.load('BrokerUI/one_hot_encoder.pkl')
    columns_to_fit=['spell','sublocality_level','rooms','bathrooms','furnished','constructionstatus','project','type']
    t=pd.DataFrame(one_hot_encoder.transform(df[columns_to_fit]))
    df.drop(columns_to_fit,axis=1,inplace=True)
    df=pd.concat([df,t],axis=1)
    columns_to_scale = ['lat', 'long', 'ft', 'carpetarea']
    df[columns_to_scale]=scalar_for_params.transform(df[columns_to_scale])
    df.drop(['lat','long'],axis=1,inplace=True)
    output = regressor.predict(df)
    return scalar_for_price.inverse_transform(output)


def EstatePricePrediction(request):
    if request.method=='POST':
        form=PredictionForm(request.POST)
        if form.is_valid():
            mydict=(request.POST).dict()
            df = pd.DataFrame(mydict,index=[0])
            columns_to_fit=['spell','sublocality_level','rooms','bathrooms','furnished','constructionstatus','project','type']
            df['rooms']=np.float64(df['rooms'])
            df['bathrooms']=np.float64(df['bathrooms'])
            df=df.loc[:,'spell':]
            print(df['rooms'].dtype)
            # print(df['spell'])
            output = processing(df)
            messages.success(request,'Output Status: Rs {}'.format(np.round(output[0],2)))


    form=PredictionForm()
    return render(request,'BrokerUI/predform.html',{'form':form})

def query(request):
    qs = Estate.objects.all()
    broker_firstname_query = request.GET.get('broker_firstname_contains')
    broker_lastname_query = request.GET.get('broker_lastname_contains')
    project_name_query = request.GET.get('project')
    min_price_query,max_price_query,min_bedroom,max_bedroom,min_bathroom,max_bathroom,min_carpetarea,max_carpetarea,min_floorarea,max_floorarea = request.GET.get('min_price'),request.GET.get('max_price'),request.GET.get('min_bedroom'),request.GET.get('max_bedroom'),request.GET.get('min_bathroom'),request.GET.get('max_bathroom'),request.GET.get('min_carpetarea'),request.GET.get('max_carpetarea'),request.GET.get('min_floorarea'),request.GET.get('max_floorarea')
    if broker_firstname_query !='' and broker_firstname_query is not None:
        qs = qs.filter(broker__user__first_name__icontains=broker_firstname_query)
    if broker_lastname_query !='' and broker_lastname_query is not None:
        qs = qs.filter(broker__user__last_name__icontains=broker_lastname_query)
    if min_price_query != '' and min_price_query is not None:
        qs = qs.filter(price__gte = float(min_price_query))
    if max_price_query != '' and max_price_query is not None:
        qs = qs.filter(price__lte = float(max_price_query))
    if min_bedroom != '' and min_bedroom is not None:
        qs = qs.filter(bedroom__gte = float(min_bedroom))
    if max_bedroom != '' and max_bedroom is not None:
        qs = qs.filter(bedroom__lte = float(max_bedroom))
    if min_bathroom != '' and min_bathroom is not None:
        qs = qs.filter(bathroom__gte = float(min_bathroom))
    if max_bathroom != '' and max_bathroom is not None:
        qs = qs.filter(bathroom__lte = float(max_bathroom))
    if min_carpetarea != '' and min_carpetarea is not None:
        qs = qs.filter(carpetarea__gte=float(min_carpetarea))
    if max_carpetarea != '' and max_carpetarea is not None:
        qs = qs.filter(carpetarea__lte=float(max_carpetarea))
    if min_floorarea != '' and min_floorarea is not None:
        qs = qs.filter(builtuparea__gte=float(min_floorarea))
    if max_floorarea != '' and max_floorarea is not None:
        qs = qs.filter(builtuparea__lte=float(max_floorarea))


    context={
        'queryset':qs
    }
    return render(request,'BrokerUI/query.html',context)

BrokerUI/templates/BrokerUI/broker_detail.html
{% extends 'SellerUI/base.html' %}
{% load static %}

{% block bodyblock %}

    <div class="jumbotron" style = "background : white">
        <div class="card testimonial-card mb-4" id = 'about' style="margin-left:30%; margin-right:30%">
          <br/>
            <div class="avatar mx-auto white" >
                {% if profile.profile_image %}
                <img src="/media/{{profile.profile_image}}" class="rounded-circle"
                alt="user" width="100" height="100">
                {% else %}
                <img src="{% static "media/blank-user.jpg" %}" class="rounded-circle"
                alt="user" width="100" height="100">
                {% endif %}
            </div>
            <br/>
            <div class="card-body">
                <h5 style="text-align:center;">{{profile.user.first_name}} {{profile.user.last_name}}</h5>
                <p>Email: {{profile.user.email}}</p>
                <p>phone number : {{profile.phone_number}}</p>
                <p>type : {{profile.type}}</p>
                <hr>
            </div>
        </div>
        {% ifequal profile.user.username user.username %}
        <button type="button"><a href="{% url 'broker_update' pk=profile.pk %}">Update</a></button>
    {% else %}
    <button type="button"><a href="{% url 'home' %}">Continue</a></button>
    {% endifequal %}
    </div>
{% endblock %}

BrokerUI/templates/BrokerUI/estate_list1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'BrokerUI/style.css' %}">
    <title>Document</title>
</head>
<body>

<div class='middle-container bg'>
    <!--  <div class='outerbody'> -->
        <nav class="nav-bg height">
            <div class='top-left'>
                <a href="{% url 'home' %}" >
                    <button class="btn btn-outline top-margin bigger-font" type="button">Home</button>
                </a>
                <a href="{% url 'query' %}" >
                    <button class="btn btn-outline top-margin bigger-font" type="button">Search</button>
                </a>
                <a href="{% url 'predform' %}" >
                    <button class="btn btn-outline top-margin bigger-font" type="button">Prediction</button>
                </a>
            </div>
            <div class='top-right' style="float:right;">
                {% if user.is_authenticated%}
                    <h3 class="float-right font-color">Welcome {{user.first_name}}</h3>
                    <h5 right-align> <a href="{% url 'logout' %}">Logout</a></h5>
                {% else %}
                    <a href="{% url 'login' %}">
                        <button class="btn btn-outline bigger-font" type="button">Login</button>
                    </a>
                    <a href="{% url 'new_user' %}">
                        <button class="btn btn-outline bigger-font right-align" type="button">SignUp</button>
                    </a>
                {% endif%}
            </div>

        </nav>
    <!-- </div> -->
    <div class='empty'></div>


    {% block content%}

        <div class='estate bg'>
            <h4 class='font-color'>List of the available estates</h4></br>
            <ol class='centre-align' type="1">
            {% for e in estate_list%}

            <li><a class='li-a' href="{% url 'estate_detail' pk=e.pk%}"><span class='price'>Rs{{e.price}}</span>  </a>
            </br><span class='li-item'>{{e.bedroom}} beds    {{e.bathroom}} ba    {{e.carpetarea}} ft2</span>
            </br><span class='li-comment'>{{e.comment}}</span>
            </li>
            </br>
            {% empty%}
                <h5 class='font-color'>No estate registered yet</h5>
            {% endfor %}
            </ol>



            <div class="pagination centre-align">
                <span class="step-links centre-align">
                    {% if page_obj.has_previous %}
                        <a class='btn btn-outline medium-font' href="?page=1">&laquo; first</a>
                        <a class='btn btn-outline medium-font' href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="btn btn-page bigger-font">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a class='btn btn-outline medium-font' id='topalign' href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class='btn btn-outline medium-font' href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                {% if user.is_authenticated%}
                <a href="{% url 'new_estate' %}">
                <button type='button' class='btn btn-outline bigger-font '>Add new estate</button></a>
            {% endif%}
            </div>

            </br>

        </div>
    {% endblock %}
</div>

</body>
</html>

BrokerUI/templates/BrokerUI/estate_list_dup.html
<div class="container">
    {% if user.is_authenticated%}
<h2>Welcome {{user.first_name}}</h2>
{% endif%}
<h2>List of the available estates</h2>
<ol type="1">
{% for e in estate_list%}

<li><a href="{% url 'estate_detail' pk=e.pk%}">Rs{{e.price}}  {{e.bedroom}}  {{e.area}}</a></li>
</br>
{% empty%}
    <h4>No estate registered yet</h4>
{% endfor %}
</ol>
{% if user.is_authenticated == False %}
    <button><a href="{% url 'login' %}">Login</a></button>
    <button><a href="{% url 'user_details' %}">SignUp</a></button>
{% else %}
    <button type='button'><a href="{% url 'new_estate' %}">New Estate</a></button>
    <h3>Change user <a href="{% url 'logout' %}">Logout</a></h3>
{% endif%}

BrokerUI/templates/BrokerUI/query1.html
{% extends 'BrokerUI/estate_list.html' %}
{% block content%}
    <h4 style="color: blanchedalmond;">Filter estates</h4>
    <form method="GET">

        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="broker_firstname_contains" placeholder="Broker firstname contains...">
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                             <i class="fa fa-search"></i>
                        </div>

                    </span>
                </div>
            </div>
        </div>


        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="broker_lastname_contains" placeholder="Broker lastname contains...">
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                             <i class="fa fa-search"></i>
                        </div>

                    </span>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="project" placeholder="Project name contains...">
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                             <i class="fa fa-search"></i>
                        </div>

                    </span>
                </div>
            </div>
        </div>


        <div class="form-row">
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputEmail4"><span style="color: rgb(196, 218, 175);">min price</span></label>
            <input type="number" class="form-control" name="min_price" id="inputEmail4" placeholder="0">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">max price</span></label>
            <input type="number" class="form-control" id="inputPassword4" name="max_price" placeholder="5000000 ">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">min bedroom</span></label>
            <input type="number" class="form-control" id="inputPassword4" name="min_bedroom" placeholder="0">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">max bedroom</span></label>
            <input type="number" class="form-control" id="inputPassword4" name="max_bedroom" placeholder="3">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">min bathroom</span></label>
            <input type="number" class="form-control" id="inputPassword4" name="min_bathroom" placeholder="0">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">max bathroom</span></label>
            <input type="number" class="form-control" id="inputPassword4" name="max_bathroom" placeholder="5">
          </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-3 col-lg-3">
              <label for="inputEmail4"><span style="color: rgb(196, 218, 175);">min carpetarea</span></label>
              <input type="number" class="form-control" id="inputEmail4" name="min_carpetarea" placeholder="0">
            </div>
            <div class="form-group col-md-3 col-lg-3">
              <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">max carpetarea</span></label>
              <input type="number" class="form-control" id="inputPassword4" name="max_carpetarea" placeholder="5000000 ">
            </div>
            <div class="form-group col-md-3 col-lg-3">
              <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">min floorarea</span></label>
              <input type="number" class="form-control" id="inputPassword4" name="min_floorarea" placeholder="0">
            </div>
            <div class="form-group col-md-3 col-lg-3">
              <label for="inputPassword4"><span style="color: rgb(196, 218, 175);">max floorarea</span></label>
              <input type="number" class="form-control" id="inputPassword4" name="max_floorarea" placeholder="3">
            </div>
        </div>




        <!-- <div class="form-row">
          <div class="form-group col-md-4">
            <label for="inputState">State</label>
            <select id="inputState" class="form-control">
              <option selected>Choose...</option>
              <option>...</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="form-check">
          <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label> -->
          <!-- </div>
        </div> -->
        <button type="submit" class="btn btn-primary">Search</button>
      </form>

    <hr><hr>
    <div class="row">
        <ul>
    {% for estate in queryset %}
        <li class="centre-align">
            <span style="color: rgb(160, 188, 240); font-weight: bold; text-decoration: underline;">  Broker name</span> : <span style="color: rgb(223, 230, 236);">{{estate.broker.user.first_name}} {{broker.user.last_name}} ; </span>
            <span style="color: rgb(160, 188, 240); font-weight: bold;margin-left: 10px; text-decoration: underline;">  Bedrooms</span> : <span style="color: aliceblue;">{{estate.bedroom}} ; </span>
            <span style="color: rgb(160, 188, 240); font-weight: bold;margin-left: 10px; text-decoration: underline;">  Bathrooms</span> : <span style="color: aliceblue;">{{estate.bathroom}} ; </span>
            <span style="color: rgb(160, 188, 240); font-weight: bold;margin-left: 10px; text-decoration: underline;">  Carpetarea</span> : <span style="color: aliceblue;">{{estate.carpetarea}} ft ; </span>
            <span style="color: rgb(160, 188, 240); font-weight: bold;margin-left: 10px; text-decoration: underline;">  Builtuparea</span> : <span style="color: aliceblue;">{{estate.builtuparea}} ft ; </span>
            <span style="color: rgb(160, 188, 240); font-weight: bold;margin-left: 10px; text-decoration: underline;">  Price</span> : <span style="color: aliceblue;">Rs {{estate.price}}</span>
        </li><hr>
    {% endfor %}
        </ul>
    </div>
{% endblock %}